### ISSUE TITLE
Adjust speaker's name

### ISSUE THREAD

**Issue by matheusazzi** [braziljs/front-in-poa#8]
Estava olhando o site e notei uma informação incorreta.

![screen shot 2015-11-29 at 22 14 48](https://cloud.githubusercontent.com/assets/1292945/11461252/a9230e0c-96e6-11e5-88be-fc9a8d50cb01.png)

Alterar o nome do speaker para Matheus Azzi e adicionar "**end**" (Front-end) no fim do parágrafo de descrição da talk.

@EvandroLG

**Comment by EvandroLG** [comment]
vlw, cara! ;)

**Comment by matheusazzi** [comment]
@EvandroLG  vc botou Lucas Azzi sahuhsau
https://github.com/braziljs/front-in-poa/commit/9646fc6cd50f37115addfa0bf821a0bc617c6f0d

**Comment by EvandroLG** [comment]
thanks, man!
